###############################################################
#  Generated by:      Cadence Innovus 17.11-s080_1
#  OS:                Linux x86_64(Host ID cad29)
#  Generated on:      Thu Mar 25 18:17:23 2021
#  Design:            CHIP
#  Command:           create_ccopt_clock_tree_spec -file ccopt.spec
###############################################################
#-------------------------------------------------------------------------------
# Clock tree setup script - dialect: Innovus
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------

namespace eval ::ccopt {}
namespace eval ::ccopt::ilm {}
set ::ccopt::ilm::ccoptSpecRestoreData {}
# Start by checking for unflattened ILMs.
# Will flatten if so and then check the db sync.
if { [catch {ccopt_check_and_flatten_ilms_no_restore}] } {
  return -code error
}
# cache the value of the restore command output by the ILM flattening code
set ::ccopt::ilm::ccoptSpecRestoreData $::ccopt::ilm::ccoptRestoreILMState

# Input pins determined constant across all timing configs.
set_ccopt_property case_analysis -pin ipad_clk_p_i/PD 0
set_ccopt_property case_analysis -pin ipad_clk_p_i/PU 0
set_ccopt_property case_analysis -pin ipad_clk_p_i/SMT 0

# Clocks present at pin clk_p_i
#   clk_p_i (period 10.000ns) in timing_config func_mode([design/CHIP.sdc])
#   clk_p_i (period 10.000ns) in timing_config scan_mode([design/CHIP.sdc])
create_ccopt_clock_tree -name clk_p_i -source clk_p_i -no_skew_group

# Clock period setting for source pin of clk_p_i
set_ccopt_property clock_period -pin clk_p_i 10

# Skew group to balance non generated clock:clk_p_i in timing_config:func_mode (sdc design/CHIP.sdc)
create_ccopt_skew_group -name clk_p_i/func_mode -sources clk_p_i -auto_sinks
set_ccopt_property include_source_latency -skew_group clk_p_i/func_mode true
set_ccopt_property target_insertion_delay -skew_group clk_p_i/func_mode 0.500
set_ccopt_property extracted_from_clock_name -skew_group clk_p_i/func_mode clk_p_i
set_ccopt_property extracted_from_constraint_mode_name -skew_group clk_p_i/func_mode func_mode
set_ccopt_property extracted_from_delay_corners -skew_group clk_p_i/func_mode {DC_max DC_min}

# Skew group to balance non generated clock:clk_p_i in timing_config:scan_mode (sdc design/CHIP.sdc)
create_ccopt_skew_group -name clk_p_i/scan_mode -sources clk_p_i -auto_sinks
set_ccopt_property include_source_latency -skew_group clk_p_i/scan_mode true
set_ccopt_property target_insertion_delay -skew_group clk_p_i/scan_mode 0.500
set_ccopt_property extracted_from_clock_name -skew_group clk_p_i/scan_mode clk_p_i
set_ccopt_property extracted_from_constraint_mode_name -skew_group clk_p_i/scan_mode scan_mode
set_ccopt_property extracted_from_delay_corners -skew_group clk_p_i/scan_mode {DC_max DC_min}


check_ccopt_clock_tree_convergence
# Restore the ILM status if possible
if { [get_ccopt_property auto_design_state_for_ilms] == 0 } {
  if {$::ccopt::ilm::ccoptSpecRestoreData != {} } {
    eval $::ccopt::ilm::ccoptSpecRestoreData
  }
}

