/*
###############################################################
#  Generated by:      Cadence Innovus 17.11-s080_1
#  OS:                Linux x86_64(Host ID cad29)
#  Generated on:      Thu Mar 25 18:22:08 2021
#  Design:            CHIP
#  Command:           saveNetlist CHIP.v
###############################################################
*/
/////////////////////////////////////////////////////////////
// Created by: Synopsys DC Expert(TM) in wire load mode
// Version   : N-2017.09-SP2
// Date      : Thu Mar 18 11:32:45 2021
/////////////////////////////////////////////////////////////
module alu_DW01_add_0 (
	A, 
	B, 
	CI, 
	SUM, 
	CO);
   input [8:0] A;
   input [8:0] B;
   input CI;
   output [8:0] SUM;
   output CO;

   // Internal wires
   wire n1;
   wire [8:1] carry;

   FA1S U1_6 (.S(SUM[6]),
	.CO(carry[7]),
	.A(A[6]),
	.B(B[6]),
	.CI(carry[6]));
   FA1S U1_5 (.S(SUM[5]),
	.CO(carry[6]),
	.A(A[5]),
	.B(B[5]),
	.CI(carry[5]));
   FA1S U1_4 (.S(SUM[4]),
	.CO(carry[5]),
	.A(A[4]),
	.B(B[4]),
	.CI(carry[4]));
   FA1S U1_3 (.S(SUM[3]),
	.CO(carry[4]),
	.A(A[3]),
	.B(B[3]),
	.CI(carry[3]));
   FA1S U1_2 (.S(SUM[2]),
	.CO(carry[3]),
	.A(A[2]),
	.B(B[2]),
	.CI(carry[2]));
   FA1S U1_1 (.S(SUM[1]),
	.CO(carry[2]),
	.A(A[1]),
	.B(B[1]),
	.CI(n1));
   FA1S U1_7 (.S(SUM[7]),
	.CO(SUM[8]),
	.A(A[7]),
	.B(B[7]),
	.CI(carry[7]));
   AN2 U1 (.O(n1),
	.I1(B[0]),
	.I2(A[0]));
   XOR2HS U2 (.O(SUM[0]),
	.I1(B[0]),
	.I2(A[0]));
endmodule

module alu_DW01_sub_0 (
	A, 
	B, 
	CI, 
	DIFF, 
	CO);
   input [8:0] A;
   input [8:0] B;
   input CI;
   output [8:0] DIFF;
   output CO;

   // Internal wires
   wire n1;
   wire n2;
   wire n3;
   wire n4;
   wire n5;
   wire n6;
   wire n7;
   wire n8;
   wire n9;
   wire [9:0] carry;

   FA1S U2_7 (.S(DIFF[7]),
	.CO(carry[8]),
	.A(A[7]),
	.B(n2),
	.CI(carry[7]));
   FA1S U2_6 (.S(DIFF[6]),
	.CO(carry[7]),
	.A(A[6]),
	.B(n3),
	.CI(carry[6]));
   FA1S U2_5 (.S(DIFF[5]),
	.CO(carry[6]),
	.A(A[5]),
	.B(n4),
	.CI(carry[5]));
   FA1S U2_4 (.S(DIFF[4]),
	.CO(carry[5]),
	.A(A[4]),
	.B(n5),
	.CI(carry[4]));
   FA1S U2_3 (.S(DIFF[3]),
	.CO(carry[4]),
	.A(A[3]),
	.B(n6),
	.CI(carry[3]));
   FA1S U2_2 (.S(DIFF[2]),
	.CO(carry[3]),
	.A(A[2]),
	.B(n7),
	.CI(carry[2]));
   FA1S U2_1 (.S(DIFF[1]),
	.CO(carry[2]),
	.A(A[1]),
	.B(n8),
	.CI(carry[1]));
   XNR2HS U1 (.O(DIFF[0]),
	.I1(n9),
	.I2(A[0]));
   INV1S U2 (.O(n9),
	.I(B[0]));
   INV1S U3 (.O(n8),
	.I(B[1]));
   INV1S U4 (.O(n7),
	.I(B[2]));
   INV1S U5 (.O(n6),
	.I(B[3]));
   INV1S U6 (.O(n5),
	.I(B[4]));
   INV1S U7 (.O(n4),
	.I(B[5]));
   INV1S U8 (.O(n3),
	.I(B[6]));
   INV1S U9 (.O(n2),
	.I(B[7]));
   INV1S U10 (.O(n1),
	.I(A[0]));
   ND2 U11 (.O(carry[1]),
	.I1(B[0]),
	.I2(n1));
   INV1S U12 (.O(DIFF[8]),
	.I(carry[8]));
endmodule

module alu_DW01_inc_0 (
	A, 
	SUM);
   input [7:0] A;
   output [7:0] SUM;

   // Internal wires
   wire [7:2] carry;

   HA1 U1_1_6 (.S(SUM[6]),
	.C(carry[7]),
	.A(A[6]),
	.B(carry[6]));
   HA1 U1_1_5 (.S(SUM[5]),
	.C(carry[6]),
	.A(A[5]),
	.B(carry[5]));
   HA1 U1_1_4 (.S(SUM[4]),
	.C(carry[5]),
	.A(A[4]),
	.B(carry[4]));
   HA1 U1_1_3 (.S(SUM[3]),
	.C(carry[4]),
	.A(A[3]),
	.B(carry[3]));
   HA1 U1_1_2 (.S(SUM[2]),
	.C(carry[3]),
	.A(A[2]),
	.B(carry[2]));
   HA1 U1_1_1 (.S(SUM[1]),
	.C(carry[2]),
	.A(A[1]),
	.B(A[0]));
   XOR2HS U1 (.O(SUM[7]),
	.I1(carry[7]),
	.I2(A[7]));
endmodule

module alu_DW_mult_uns_0 (
	a, 
	b, 
	product);
   input [7:0] a;
   input [7:0] b;
   output [15:0] product;

   // Internal wires
   wire n2;
   wire n3;
   wire n4;
   wire n5;
   wire n6;
   wire n7;
   wire n8;
   wire n9;
   wire n10;
   wire n11;
   wire n12;
   wire n13;
   wire n14;
   wire n15;
   wire n16;
   wire n17;
   wire n18;
   wire n19;
   wire n20;
   wire n21;
   wire n22;
   wire n23;
   wire n24;
   wire n25;
   wire n26;
   wire n27;
   wire n28;
   wire n29;
   wire n30;
   wire n31;
   wire n32;
   wire n33;
   wire n34;
   wire n35;
   wire n36;
   wire n37;
   wire n38;
   wire n39;
   wire n40;
   wire n41;
   wire n42;
   wire n43;
   wire n44;
   wire n45;
   wire n46;
   wire n47;
   wire n48;
   wire n49;
   wire n50;
   wire n51;
   wire n52;
   wire n53;
   wire n54;
   wire n55;
   wire n56;
   wire n57;
   wire n58;
   wire n59;
   wire n60;
   wire n61;
   wire n62;
   wire n63;
   wire n64;
   wire n65;
   wire n66;
   wire n67;
   wire n68;
   wire n69;
   wire n70;
   wire n71;
   wire n72;
   wire n73;
   wire n74;
   wire n75;
   wire n76;
   wire n77;
   wire n78;
   wire n79;
   wire n80;
   wire n81;
   wire n82;
   wire n83;
   wire n84;
   wire n85;
   wire n86;
   wire n87;
   wire n88;
   wire n89;
   wire n90;
   wire n91;
   wire n92;
   wire n93;
   wire n94;
   wire n95;
   wire n96;
   wire n97;
   wire n98;
   wire n99;
   wire n100;
   wire n101;
   wire n102;
   wire n103;
   wire n104;
   wire n105;
   wire n106;
   wire n107;
   wire n108;
   wire n109;
   wire n110;
   wire n111;
   wire n112;
   wire n113;
   wire n114;
   wire n115;
   wire n116;
   wire n117;
   wire n118;
   wire n119;
   wire n120;
   wire n121;
   wire n122;
   wire n123;
   wire n124;
   wire n125;
   wire n126;
   wire n127;
   wire n128;
   wire n129;
   wire n130;
   wire n131;
   wire n132;
   wire n133;
   wire n134;
   wire n135;
   wire n136;
   wire n137;
   wire n138;
   wire n139;
   wire n140;
   wire n141;
   wire n142;
   wire n143;
   wire n144;
   wire n145;
   wire n146;
   wire n147;
   wire n148;
   wire n149;
   wire n150;
   wire n151;
   wire n152;
   wire n153;
   wire n154;
   wire n155;
   wire n156;
   wire n157;
   wire n158;
   wire n159;
   wire n160;
   wire n161;
   wire n246;
   wire n247;

   FA1S U2 (.S(product[14]),
	.CO(product[15]),
	.A(n99),
	.B(n15),
	.CI(n2));
   FA1S U3 (.S(product[13]),
	.CO(n2),
	.A(n16),
	.B(n17),
	.CI(n3));
   FA1S U4 (.S(product[12]),
	.CO(n3),
	.A(n18),
	.B(n21),
	.CI(n4));
   FA1S U5 (.S(product[11]),
	.CO(n4),
	.A(n27),
	.B(n22),
	.CI(n5));
   FA1S U6 (.S(product[10]),
	.CO(n5),
	.A(n35),
	.B(n28),
	.CI(n6));
   FA1S U7 (.S(product[9]),
	.CO(n6),
	.A(n45),
	.B(n36),
	.CI(n7));
   FA1S U8 (.S(product[8]),
	.CO(n7),
	.A(n57),
	.B(n46),
	.CI(n8));
   FA1S U9 (.S(product[7]),
	.CO(n8),
	.A(n69),
	.B(n58),
	.CI(n9));
   FA1S U10 (.S(product[6]),
	.CO(n9),
	.A(n79),
	.B(n70),
	.CI(n10));
   FA1S U11 (.S(product[5]),
	.CO(n10),
	.A(n87),
	.B(n80),
	.CI(n11));
   FA1S U12 (.S(product[4]),
	.CO(n11),
	.A(n93),
	.B(n88),
	.CI(n12));
   FA1S U13 (.S(product[3]),
	.CO(n12),
	.A(n96),
	.B(n13),
	.CI(n94));
   FA1S U14 (.S(product[2]),
	.CO(n13),
	.A(n146),
	.B(n14),
	.CI(n98));
   HA1 U15 (.S(product[1]),
	.C(n14),
	.A(n154),
	.B(n161));
   FA1S U16 (.S(n16),
	.CO(n15),
	.A(n107),
	.B(n100),
	.CI(n19));
   FA1S U17 (.S(n18),
	.CO(n17),
	.A(n25),
	.B(n20),
	.CI(n23));
   FA1S U18 (.S(n20),
	.CO(n19),
	.A(n115),
	.B(n101),
	.CI(n108));
   FA1S U19 (.S(n22),
	.CO(n21),
	.A(n31),
	.B(n24),
	.CI(n29));
   FA1S U20 (.S(n24),
	.CO(n23),
	.A(n116),
	.B(n33),
	.CI(n26));
   FA1S U21 (.S(n26),
	.CO(n25),
	.A(n123),
	.B(n102),
	.CI(n109));
   FA1S U22 (.S(n28),
	.CO(n27),
	.A(n32),
	.B(n37),
	.CI(n30));
   FA1S U23 (.S(n30),
	.CO(n29),
	.A(n41),
	.B(n34),
	.CI(n39));
   FA1S U24 (.S(n32),
	.CO(n31),
	.A(n124),
	.B(n117),
	.CI(n43));
   FA1S U25 (.S(n34),
	.CO(n33),
	.A(n131),
	.B(n103),
	.CI(n110));
   FA1S U26 (.S(n36),
	.CO(n35),
	.A(n40),
	.B(n47),
	.CI(n38));
   FA1S U27 (.S(n38),
	.CO(n37),
	.A(n44),
	.B(n51),
	.CI(n49));
   FA1S U28 (.S(n40),
	.CO(n39),
	.A(n55),
	.B(n53),
	.CI(n42));
   FA1S U29 (.S(n42),
	.CO(n41),
	.A(n118),
	.B(n125),
	.CI(n132));
   FA1S U30 (.S(n44),
	.CO(n43),
	.A(n139),
	.B(n104),
	.CI(n111));
   FA1S U31 (.S(n46),
	.CO(n45),
	.A(n50),
	.B(n59),
	.CI(n48));
   FA1S U32 (.S(n48),
	.CO(n47),
	.A(n54),
	.B(n52),
	.CI(n61));
   FA1S U33 (.S(n50),
	.CO(n49),
	.A(n56),
	.B(n65),
	.CI(n63));
   FA1S U34 (.S(n52),
	.CO(n51),
	.A(n140),
	.B(n133),
	.CI(n67));
   FA1S U35 (.S(n54),
	.CO(n53),
	.A(n126),
	.B(n119),
	.CI(n147));
   HA1 U36 (.S(n56),
	.C(n55),
	.A(n112),
	.B(n105));
   FA1S U37 (.S(n58),
	.CO(n57),
	.A(n71),
	.B(n62),
	.CI(n60));
   FA1S U38 (.S(n60),
	.CO(n59),
	.A(n64),
	.B(n66),
	.CI(n73));
   FA1S U39 (.S(n62),
	.CO(n61),
	.A(n77),
	.B(n68),
	.CI(n75));
   FA1S U40 (.S(n64),
	.CO(n63),
	.A(n141),
	.B(n127),
	.CI(n134));
   FA1S U41 (.S(n66),
	.CO(n65),
	.A(n155),
	.B(n120),
	.CI(n148));
   HA1 U42 (.S(n68),
	.C(n67),
	.A(n113),
	.B(n106));
   FA1S U43 (.S(n70),
	.CO(n69),
	.A(n81),
	.B(n74),
	.CI(n72));
   FA1S U44 (.S(n72),
	.CO(n71),
	.A(n78),
	.B(n83),
	.CI(n76));
   FA1S U45 (.S(n74),
	.CO(n73),
	.A(n142),
	.B(n135),
	.CI(n85));
   FA1S U46 (.S(n76),
	.CO(n75),
	.A(n156),
	.B(n128),
	.CI(n149));
   HA1 U47 (.S(n78),
	.C(n77),
	.A(n121),
	.B(n114));
   FA1S U48 (.S(n80),
	.CO(n79),
	.A(n89),
	.B(n84),
	.CI(n82));
   FA1S U49 (.S(n82),
	.CO(n81),
	.A(n150),
	.B(n91),
	.CI(n86));
   FA1S U50 (.S(n84),
	.CO(n83),
	.A(n157),
	.B(n136),
	.CI(n143));
   HA1 U51 (.S(n86),
	.C(n85),
	.A(n129),
	.B(n122));
   FA1S U52 (.S(n88),
	.CO(n87),
	.A(n95),
	.B(n92),
	.CI(n90));
   FA1S U53 (.S(n90),
	.CO(n89),
	.A(n158),
	.B(n144),
	.CI(n151));
   HA1 U54 (.S(n92),
	.C(n91),
	.A(n137),
	.B(n130));
   FA1S U55 (.S(n94),
	.CO(n93),
	.A(n159),
	.B(n152),
	.CI(n97));
   HA1 U56 (.S(n96),
	.C(n95),
	.A(n145),
	.B(n138));
   HA1 U57 (.S(n98),
	.C(n97),
	.A(n160),
	.B(n153));
   INV1S U172 (.O(n246),
	.I(b[0]));
   INV1S U173 (.O(n247),
	.I(a[0]));
   NR2 U174 (.O(product[0]),
	.I1(n247),
	.I2(n246));
   NR2 U175 (.O(n99),
	.I1(a[7]),
	.I2(b[7]));
   NR2 U176 (.O(n161),
	.I1(n247),
	.I2(b[1]));
   NR2 U177 (.O(n160),
	.I1(n247),
	.I2(b[2]));
   NR2 U178 (.O(n159),
	.I1(n247),
	.I2(b[3]));
   NR2 U179 (.O(n158),
	.I1(n247),
	.I2(b[4]));
   NR2 U180 (.O(n157),
	.I1(n247),
	.I2(b[5]));
   NR2 U181 (.O(n156),
	.I1(n247),
	.I2(b[6]));
   NR2 U182 (.O(n155),
	.I1(n247),
	.I2(b[7]));
   NR2 U183 (.O(n154),
	.I1(n246),
	.I2(a[1]));
   NR2 U184 (.O(n153),
	.I1(b[1]),
	.I2(a[1]));
   NR2 U185 (.O(n152),
	.I1(b[2]),
	.I2(a[1]));
   NR2 U186 (.O(n151),
	.I1(b[3]),
	.I2(a[1]));
   NR2 U187 (.O(n150),
	.I1(b[4]),
	.I2(a[1]));
   NR2 U188 (.O(n149),
	.I1(b[5]),
	.I2(a[1]));
   NR2 U189 (.O(n148),
	.I1(b[6]),
	.I2(a[1]));
   NR2 U190 (.O(n147),
	.I1(b[7]),
	.I2(a[1]));
   NR2 U191 (.O(n146),
	.I1(n246),
	.I2(a[2]));
   NR2 U192 (.O(n145),
	.I1(b[1]),
	.I2(a[2]));
   NR2 U193 (.O(n144),
	.I1(b[2]),
	.I2(a[2]));
   NR2 U194 (.O(n143),
	.I1(b[3]),
	.I2(a[2]));
   NR2 U195 (.O(n142),
	.I1(b[4]),
	.I2(a[2]));
   NR2 U196 (.O(n141),
	.I1(b[5]),
	.I2(a[2]));
   NR2 U197 (.O(n140),
	.I1(b[6]),
	.I2(a[2]));
   NR2 U198 (.O(n139),
	.I1(b[7]),
	.I2(a[2]));
   NR2 U199 (.O(n138),
	.I1(n246),
	.I2(a[3]));
   NR2 U200 (.O(n137),
	.I1(b[1]),
	.I2(a[3]));
   NR2 U201 (.O(n136),
	.I1(b[2]),
	.I2(a[3]));
   NR2 U202 (.O(n135),
	.I1(b[3]),
	.I2(a[3]));
   NR2 U203 (.O(n134),
	.I1(b[4]),
	.I2(a[3]));
   NR2 U204 (.O(n133),
	.I1(b[5]),
	.I2(a[3]));
   NR2 U205 (.O(n132),
	.I1(b[6]),
	.I2(a[3]));
   NR2 U206 (.O(n131),
	.I1(b[7]),
	.I2(a[3]));
   NR2 U207 (.O(n130),
	.I1(n246),
	.I2(a[4]));
   NR2 U208 (.O(n129),
	.I1(b[1]),
	.I2(a[4]));
   NR2 U209 (.O(n128),
	.I1(b[2]),
	.I2(a[4]));
   NR2 U210 (.O(n127),
	.I1(b[3]),
	.I2(a[4]));
   NR2 U211 (.O(n126),
	.I1(b[4]),
	.I2(a[4]));
   NR2 U212 (.O(n125),
	.I1(b[5]),
	.I2(a[4]));
   NR2 U213 (.O(n124),
	.I1(b[6]),
	.I2(a[4]));
   NR2 U214 (.O(n123),
	.I1(b[7]),
	.I2(a[4]));
   NR2 U215 (.O(n122),
	.I1(n246),
	.I2(a[5]));
   NR2 U216 (.O(n121),
	.I1(b[1]),
	.I2(a[5]));
   NR2 U217 (.O(n120),
	.I1(b[2]),
	.I2(a[5]));
   NR2 U218 (.O(n119),
	.I1(b[3]),
	.I2(a[5]));
   NR2 U219 (.O(n118),
	.I1(b[4]),
	.I2(a[5]));
   NR2 U220 (.O(n117),
	.I1(b[5]),
	.I2(a[5]));
   NR2 U221 (.O(n116),
	.I1(b[6]),
	.I2(a[5]));
   NR2 U222 (.O(n115),
	.I1(b[7]),
	.I2(a[5]));
   NR2 U223 (.O(n114),
	.I1(n246),
	.I2(a[6]));
   NR2 U224 (.O(n113),
	.I1(b[1]),
	.I2(a[6]));
   NR2 U225 (.O(n112),
	.I1(b[2]),
	.I2(a[6]));
   NR2 U226 (.O(n111),
	.I1(b[3]),
	.I2(a[6]));
   NR2 U227 (.O(n110),
	.I1(b[4]),
	.I2(a[6]));
   NR2 U228 (.O(n109),
	.I1(b[5]),
	.I2(a[6]));
   NR2 U229 (.O(n108),
	.I1(b[6]),
	.I2(a[6]));
   NR2 U230 (.O(n107),
	.I1(b[7]),
	.I2(a[6]));
   NR2 U231 (.O(n106),
	.I1(n246),
	.I2(a[7]));
   NR2 U232 (.O(n105),
	.I1(a[7]),
	.I2(b[1]));
   NR2 U233 (.O(n104),
	.I1(a[7]),
	.I2(b[2]));
   NR2 U234 (.O(n103),
	.I1(a[7]),
	.I2(b[3]));
   NR2 U235 (.O(n102),
	.I1(a[7]),
	.I2(b[4]));
   NR2 U236 (.O(n101),
	.I1(a[7]),
	.I2(b[5]));
   NR2 U237 (.O(n100),
	.I1(a[7]),
	.I2(b[6]));
endmodule

module alu (
	clk_p_i, 
	reset_n_i, 
	data_a_i, 
	data_b_i, 
	inst_i, 
	data_o);
   input clk_p_i;
   input reset_n_i;
   input [7:0] data_a_i;
   input [7:0] data_b_i;
   input [2:0] inst_i;
   output [15:0] data_o;

   // Internal wires
   wire CTS_8;
   wire CTS_7;
   wire FE_DBTN19_data_b_r_7;
   wire FE_DBTN18_data_b_r_6;
   wire FE_DBTN17_data_b_r_5;
   wire FE_DBTN16_data_b_r_4;
   wire FE_DBTN15_data_b_r_3;
   wire FE_DBTN14_data_b_r_2;
   wire FE_DBTN13_data_b_r_1;
   wire FE_DBTN12_out_inst_3_6;
   wire FE_DBTN11_out_inst_3_5;
   wire FE_DBTN10_out_inst_3_4;
   wire FE_DBTN9_out_inst_3_3;
   wire FE_DBTN8_out_inst_3_2;
   wire FE_DBTN7_out_inst_3_1;
   wire FE_DBTN6_out_inst_3_0;
   wire FE_DBTN5_n36;
   wire FE_DBTN4_n39;
   wire FE_DBTN3_n41;
   wire FE_DBTN2_n48;
   wire FE_DBTN1_n90;
   wire FE_DBTN0_n91;
   wire \data_a_r[0] ;
   wire out_inst_1_15;
   wire FE_UNCONNECTED_1;
   wire N32;
   wire N33;
   wire N34;
   wire N35;
   wire N36;
   wire N37;
   wire N38;
   wire n2;
   wire n25;
   wire n26;
   wire n27;
   wire n28;
   wire n29;
   wire n30;
   wire n31;
   wire n32;
   wire n33;
   wire n34;
   wire n35;
   wire n36;
   wire n37;
   wire n38;
   wire n39;
   wire n40;
   wire n41;
   wire n42;
   wire n43;
   wire n44;
   wire n45;
   wire n46;
   wire n47;
   wire n48;
   wire n49;
   wire n50;
   wire n51;
   wire n52;
   wire n54;
   wire n55;
   wire n58;
   wire n59;
   wire n60;
   wire n61;
   wire n62;
   wire n63;
   wire n64;
   wire n65;
   wire n66;
   wire n67;
   wire n68;
   wire n69;
   wire n70;
   wire n71;
   wire n72;
   wire n73;
   wire n74;
   wire n75;
   wire n76;
   wire n77;
   wire n78;
   wire n79;
   wire n80;
   wire n81;
   wire n82;
   wire n83;
   wire n84;
   wire n85;
   wire n86;
   wire n87;
   wire n88;
   wire n89;
   wire N30;
   wire N29;
   wire N28;
   wire N27;
   wire N26;
   wire N25;
   wire N24;
   wire N23;
   wire n90;
   wire n91;
   wire n108;
   wire n116;
   wire n117;
   wire n118;
   wire n119;
   wire n120;
   wire n121;
   wire n122;
   wire n123;
   wire n124;
   wire [7:0] data_a_w;
   wire [7:0] data_b_w;
   wire [7:0] data_b_r;
   wire [8:0] out_inst_0;
   wire [7:0] out_inst_1;
   wire [15:0] out_inst_2;
   wire [6:0] out_inst_3;
   wire [2:0] state_r;
   wire [2:0] inst_r;

   INV12CK CTS_ccl_a_INV_clk_p_i_G0_L3_1 (.O(CTS_7),
	.I(CTS_8));
   INV6CK CTS_ccl_a_INV_clk_p_i_G0_L2_1 (.O(CTS_8),
	.I(clk_p_i));
   INV1S FE_DBTC19_data_b_r_7 (.O(FE_DBTN19_data_b_r_7),
	.I(data_b_r[7]));
   INV1S FE_DBTC18_data_b_r_6 (.O(FE_DBTN18_data_b_r_6),
	.I(data_b_r[6]));
   INV1S FE_DBTC17_data_b_r_5 (.O(FE_DBTN17_data_b_r_5),
	.I(data_b_r[5]));
   INV1S FE_DBTC16_data_b_r_4 (.O(FE_DBTN16_data_b_r_4),
	.I(data_b_r[4]));
   INV1S FE_DBTC15_data_b_r_3 (.O(FE_DBTN15_data_b_r_3),
	.I(data_b_r[3]));
   INV1S FE_DBTC14_data_b_r_2 (.O(FE_DBTN14_data_b_r_2),
	.I(data_b_r[2]));
   INV1S FE_DBTC13_data_b_r_1 (.O(FE_DBTN13_data_b_r_1),
	.I(data_b_r[1]));
   INV1S FE_DBTC12_out_inst_3_6 (.O(FE_DBTN12_out_inst_3_6),
	.I(out_inst_3[6]));
   INV1S FE_DBTC11_out_inst_3_5 (.O(FE_DBTN11_out_inst_3_5),
	.I(out_inst_3[5]));
   INV1S FE_DBTC10_out_inst_3_4 (.O(FE_DBTN10_out_inst_3_4),
	.I(out_inst_3[4]));
   INV1S FE_DBTC9_out_inst_3_3 (.O(FE_DBTN9_out_inst_3_3),
	.I(out_inst_3[3]));
   INV1S FE_DBTC8_out_inst_3_2 (.O(FE_DBTN8_out_inst_3_2),
	.I(out_inst_3[2]));
   INV1S FE_DBTC7_out_inst_3_1 (.O(FE_DBTN7_out_inst_3_1),
	.I(out_inst_3[1]));
   INV1S FE_DBTC6_out_inst_3_0 (.O(FE_DBTN6_out_inst_3_0),
	.I(out_inst_3[0]));
   INV1S FE_DBTC5_n36 (.O(FE_DBTN5_n36),
	.I(n36));
   INV1S FE_DBTC4_n39 (.O(FE_DBTN4_n39),
	.I(n39));
   INV1S FE_DBTC3_n41 (.O(FE_DBTN3_n41),
	.I(n41));
   INV1S FE_DBTC2_n48 (.O(FE_DBTN2_n48),
	.I(n48));
   INV1S FE_DBTC1_n90 (.O(FE_DBTN1_n90),
	.I(n90));
   INV1S FE_DBTC0_n91 (.O(FE_DBTN0_n91),
	.I(n91));
   ND2 U70 (.O(n26),
	.I1(inst_r[1]),
	.I2(n28));
   ND2 U71 (.O(n30),
	.I1(inst_r[0]),
	.I2(n28));
   OA222 U72 (.O(n34),
	.A1(n35),
	.A2(n36),
	.B1(n37),
	.B2(n38),
	.C1(n39),
	.C2(n117));
   AO12 U73 (.O(n44),
	.A1(n122),
	.B1(n46),
	.B2(FE_DBTN3_n41));
   ND2 U74 (.O(n31),
	.I1(inst_r[2]),
	.I2(n28));
   AO222 U80 (.O(n59),
	.A1(out_inst_2[6]),
	.A2(FE_DBTN3_n41),
	.B1(out_inst_3[6]),
	.B2(FE_DBTN5_n36),
	.C1(out_inst_0[6]),
	.C2(FE_DBTN2_n48));
   AO222 U82 (.O(n63),
	.A1(out_inst_2[5]),
	.A2(FE_DBTN3_n41),
	.B1(out_inst_3[5]),
	.B2(FE_DBTN5_n36),
	.C1(out_inst_0[5]),
	.C2(FE_DBTN2_n48));
   AO222 U84 (.O(n67),
	.A1(out_inst_2[4]),
	.A2(FE_DBTN3_n41),
	.B1(out_inst_3[4]),
	.B2(FE_DBTN5_n36),
	.C1(out_inst_0[4]),
	.C2(FE_DBTN2_n48));
   AO222 U86 (.O(n71),
	.A1(out_inst_2[3]),
	.A2(FE_DBTN3_n41),
	.B1(out_inst_3[3]),
	.B2(FE_DBTN5_n36),
	.C1(out_inst_0[3]),
	.C2(FE_DBTN2_n48));
   AO222 U88 (.O(n75),
	.A1(out_inst_2[2]),
	.A2(FE_DBTN3_n41),
	.B1(out_inst_3[2]),
	.B2(FE_DBTN5_n36),
	.C1(out_inst_0[2]),
	.C2(FE_DBTN2_n48));
   AO222 U90 (.O(n79),
	.A1(out_inst_2[1]),
	.A2(FE_DBTN3_n41),
	.B1(out_inst_3[1]),
	.B2(FE_DBTN5_n36),
	.C1(out_inst_0[1]),
	.C2(FE_DBTN2_n48));
   AO222 U98 (.O(n83),
	.A1(out_inst_2[0]),
	.A2(FE_DBTN3_n41),
	.B1(out_inst_3[0]),
	.B2(FE_DBTN5_n36),
	.C1(out_inst_0[0]),
	.C2(FE_DBTN2_n48));
   alu_DW01_add_0 add_64 (.A({ n2,
		out_inst_3,
		\data_a_r[0]  }),
	.B({ n2,
		data_b_r }),
	.CI(n2),
	.SUM(out_inst_0));
   alu_DW01_sub_0 r319 (.A({ n2,
		data_b_r }),
	.B({ n2,
		out_inst_3,
		\data_a_r[0]  }),
	.CI(n2),
	.DIFF({ out_inst_1_15,
		out_inst_1 }));
   alu_DW01_inc_0 add_0_root_add_73_ni (.A({ N23,
		N24,
		N25,
		N26,
		N27,
		N28,
		N29,
		N30 }),
	.SUM({ N38,
		N37,
		N36,
		N35,
		N34,
		N33,
		N32,
		FE_UNCONNECTED_1 }));
   alu_DW_mult_uns_0 mult_66 (.a({ FE_DBTN12_out_inst_3_6,
		FE_DBTN11_out_inst_3_5,
		FE_DBTN10_out_inst_3_4,
		FE_DBTN9_out_inst_3_3,
		FE_DBTN8_out_inst_3_2,
		FE_DBTN7_out_inst_3_1,
		FE_DBTN6_out_inst_3_0,
		\data_a_r[0]  }),
	.b({ FE_DBTN19_data_b_r_7,
		FE_DBTN18_data_b_r_6,
		FE_DBTN17_data_b_r_5,
		FE_DBTN16_data_b_r_4,
		FE_DBTN15_data_b_r_3,
		FE_DBTN14_data_b_r_2,
		FE_DBTN13_data_b_r_1,
		data_b_r[0] }),
	.product(out_inst_2));
   QDFFRBN \data_b_r_reg[7]  (.Q(data_b_r[7]),
	.D(data_b_w[7]),
	.CK(CTS_7),
	.RB(reset_n_i));
   QDFFRBN \data_b_r_reg[6]  (.Q(data_b_r[6]),
	.D(data_b_w[6]),
	.CK(CTS_7),
	.RB(reset_n_i));
   QDFFRBN \data_b_r_reg[5]  (.Q(data_b_r[5]),
	.D(data_b_w[5]),
	.CK(CTS_7),
	.RB(reset_n_i));
   QDFFRBN \data_b_r_reg[4]  (.Q(data_b_r[4]),
	.D(data_b_w[4]),
	.CK(CTS_7),
	.RB(reset_n_i));
   QDFFRBN \data_b_r_reg[3]  (.Q(data_b_r[3]),
	.D(data_b_w[3]),
	.CK(CTS_7),
	.RB(reset_n_i));
   QDFFRBN \data_b_r_reg[2]  (.Q(data_b_r[2]),
	.D(data_b_w[2]),
	.CK(CTS_7),
	.RB(reset_n_i));
   QDFFRBN \data_b_r_reg[1]  (.Q(data_b_r[1]),
	.D(data_b_w[1]),
	.CK(CTS_7),
	.RB(reset_n_i));
   QDFFRBN \data_a_r_reg[7]  (.Q(out_inst_3[6]),
	.D(data_a_w[7]),
	.CK(CTS_7),
	.RB(reset_n_i));
   QDFFRBN \data_a_r_reg[6]  (.Q(out_inst_3[5]),
	.D(data_a_w[6]),
	.CK(CTS_7),
	.RB(reset_n_i));
   QDFFRBN \data_a_r_reg[5]  (.Q(out_inst_3[4]),
	.D(data_a_w[5]),
	.CK(CTS_7),
	.RB(reset_n_i));
   QDFFRBN \data_a_r_reg[4]  (.Q(out_inst_3[3]),
	.D(data_a_w[4]),
	.CK(CTS_7),
	.RB(reset_n_i));
   QDFFRBN \data_a_r_reg[3]  (.Q(out_inst_3[2]),
	.D(data_a_w[3]),
	.CK(CTS_7),
	.RB(reset_n_i));
   QDFFRBN \data_a_r_reg[2]  (.Q(out_inst_3[1]),
	.D(data_a_w[2]),
	.CK(CTS_7),
	.RB(reset_n_i));
   QDFFRBN \data_a_r_reg[1]  (.Q(out_inst_3[0]),
	.D(data_a_w[1]),
	.CK(CTS_7),
	.RB(reset_n_i));
   QDFFRBN \data_a_r_reg[0]  (.Q(\data_a_r[0] ),
	.D(data_a_w[0]),
	.CK(CTS_7),
	.RB(reset_n_i));
   QDFFRBN \data_b_r_reg[0]  (.Q(data_b_r[0]),
	.D(data_b_w[0]),
	.CK(CTS_7),
	.RB(reset_n_i));
   QDFFRBN \inst_r_reg[0]  (.Q(inst_r[0]),
	.D(inst_i[0]),
	.CK(CTS_7),
	.RB(reset_n_i));
   QDFFRBN \inst_r_reg[1]  (.Q(inst_r[1]),
	.D(inst_i[1]),
	.CK(CTS_7),
	.RB(reset_n_i));
   QDFFRBN \state_r_reg[0]  (.Q(state_r[0]),
	.D(n88),
	.CK(CTS_7),
	.RB(reset_n_i));
   QDFFRBN \state_r_reg[2]  (.Q(state_r[2]),
	.D(n89),
	.CK(CTS_7),
	.RB(reset_n_i));
   QDFFRBN \state_r_reg[1]  (.Q(state_r[1]),
	.D(n87),
	.CK(CTS_7),
	.RB(reset_n_i));
   QDFFRBN \inst_r_reg[2]  (.Q(inst_r[2]),
	.D(inst_i[2]),
	.CK(CTS_7),
	.RB(reset_n_i));
   QDFFRBN \reg_data_a_reg[7]  (.Q(data_a_w[7]),
	.D(data_a_i[7]),
	.CK(CTS_7),
	.RB(reset_n_i));
   QDFFRBN \reg_data_a_reg[6]  (.Q(data_a_w[6]),
	.D(data_a_i[6]),
	.CK(CTS_7),
	.RB(reset_n_i));
   QDFFRBN \reg_data_a_reg[5]  (.Q(data_a_w[5]),
	.D(data_a_i[5]),
	.CK(CTS_7),
	.RB(reset_n_i));
   QDFFRBN \reg_data_a_reg[4]  (.Q(data_a_w[4]),
	.D(data_a_i[4]),
	.CK(CTS_7),
	.RB(reset_n_i));
   QDFFRBN \reg_data_a_reg[3]  (.Q(data_a_w[3]),
	.D(data_a_i[3]),
	.CK(CTS_7),
	.RB(reset_n_i));
   QDFFRBN \reg_data_a_reg[2]  (.Q(data_a_w[2]),
	.D(data_a_i[2]),
	.CK(CTS_7),
	.RB(reset_n_i));
   QDFFRBN \reg_data_a_reg[1]  (.Q(data_a_w[1]),
	.D(data_a_i[1]),
	.CK(CTS_7),
	.RB(reset_n_i));
   QDFFRBN \reg_data_a_reg[0]  (.Q(data_a_w[0]),
	.D(data_a_i[0]),
	.CK(CTS_7),
	.RB(reset_n_i));
   QDFFRBN \reg_data_b_reg[7]  (.Q(data_b_w[7]),
	.D(data_b_i[7]),
	.CK(CTS_7),
	.RB(reset_n_i));
   QDFFRBN \reg_data_b_reg[6]  (.Q(data_b_w[6]),
	.D(data_b_i[6]),
	.CK(CTS_7),
	.RB(reset_n_i));
   QDFFRBN \reg_data_b_reg[5]  (.Q(data_b_w[5]),
	.D(data_b_i[5]),
	.CK(CTS_7),
	.RB(reset_n_i));
   QDFFRBN \reg_data_b_reg[4]  (.Q(data_b_w[4]),
	.D(data_b_i[4]),
	.CK(CTS_7),
	.RB(reset_n_i));
   QDFFRBN \reg_data_b_reg[3]  (.Q(data_b_w[3]),
	.D(data_b_i[3]),
	.CK(CTS_7),
	.RB(reset_n_i));
   QDFFRBN \reg_data_b_reg[2]  (.Q(data_b_w[2]),
	.D(data_b_i[2]),
	.CK(CTS_7),
	.RB(reset_n_i));
   QDFFRBN \reg_data_b_reg[1]  (.Q(data_b_w[1]),
	.D(data_b_i[1]),
	.CK(CTS_7),
	.RB(reset_n_i));
   QDFFRBN \reg_data_b_reg[0]  (.Q(data_b_w[0]),
	.D(data_b_i[0]),
	.CK(CTS_7),
	.RB(reset_n_i));
   MOAI1S U99 (.O(n52),
	.A1(n47),
	.A2(n116),
	.B1(n116),
	.B2(n122));
   OA12 U100 (.O(n90),
	.A1(n47),
	.B1(out_inst_1_15),
	.B2(n38));
   OR2 U101 (.O(n91),
	.I1(n116),
	.I2(n38));
   OR2T U117 (.O(data_o[8]),
	.I1(n52),
	.I2(n108));
   AO12T U118 (.O(data_o[10]),
	.A1(n52),
	.B1(out_inst_2[10]),
	.B2(FE_DBTN3_n41));
   AO12T U119 (.O(data_o[11]),
	.A1(n52),
	.B1(out_inst_2[11]),
	.B2(FE_DBTN3_n41));
   AO12T U120 (.O(data_o[12]),
	.A1(n52),
	.B1(out_inst_2[12]),
	.B2(FE_DBTN3_n41));
   AO12T U121 (.O(data_o[13]),
	.A1(n52),
	.B1(out_inst_2[13]),
	.B2(FE_DBTN3_n41));
   AO12T U122 (.O(data_o[14]),
	.A1(n52),
	.B1(out_inst_2[14]),
	.B2(FE_DBTN3_n41));
   AO12T U123 (.O(data_o[15]),
	.A1(n52),
	.B1(out_inst_2[15]),
	.B2(FE_DBTN3_n41));
   AO12T U125 (.O(data_o[9]),
	.A1(n52),
	.B1(out_inst_2[9]),
	.B2(FE_DBTN3_n41));
   AO112T U126 (.O(data_o[7]),
	.A1(n54),
	.B1(n55),
	.C1(out_inst_0[7]),
	.C2(FE_DBTN2_n48));
   AO222S U127 (.O(n55),
	.A1(out_inst_1[7]),
	.A2(FE_DBTN1_n90),
	.B1(N38),
	.B2(FE_DBTN0_n91),
	.C1(FE_DBTN4_n39),
	.C2(n58));
   OR3B2T U128 (.O(data_o[6]),
	.I1(n59),
	.B1(n60),
	.B2(n61));
   OR3B2T U129 (.O(data_o[5]),
	.I1(n63),
	.B1(n64),
	.B2(n65));
   OR3B2T U130 (.O(data_o[4]),
	.I1(n67),
	.B1(n68),
	.B2(n69));
   OR3B2T U131 (.O(data_o[3]),
	.I1(n71),
	.B1(n72),
	.B2(n73));
   OR3B2T U132 (.O(data_o[2]),
	.I1(n75),
	.B1(n76),
	.B2(n77));
   OR3B2T U133 (.O(data_o[1]),
	.I1(n79),
	.B1(n80),
	.B2(n81));
   OR3B2T U134 (.O(data_o[0]),
	.I1(n83),
	.B1(n84),
	.B2(n85));
   INV1S U135 (.O(n116),
	.I(out_inst_1_15));
   ND3 U136 (.O(n28),
	.I1(n47),
	.I2(n48),
	.I3(n49));
   AOI22S U137 (.O(n49),
	.A1(n50),
	.A2(n43),
	.B1(n37),
	.B2(n121));
   INV1S U138 (.O(n121),
	.I(n38));
   OAI222S U139 (.O(n50),
	.A1(n40),
	.A2(n39),
	.B1(n51),
	.B2(n119),
	.C1(n118),
	.C2(n36));
   INV1S U140 (.O(n122),
	.I(n42));
   ND3 U141 (.O(n27),
	.I1(n32),
	.I2(n33),
	.I3(n34));
   AO13S U142 (.O(n33),
	.A1(n43),
	.B1(n36),
	.B2(n41),
	.B3(n42));
   AOI22S U143 (.O(n32),
	.A1(n44),
	.A2(n119),
	.B1(n45),
	.B2(n122));
   OA12 U144 (.O(n51),
	.A1(n41),
	.B1(n45),
	.B2(n42));
   OAI22S U145 (.O(n25),
	.A1(n43),
	.A2(n48),
	.B1(n47),
	.B2(n43));
   ND3 U146 (.O(n48),
	.I1(n124),
	.I2(n120),
	.I3(n123));
   INV1S U147 (.O(n118),
	.I(n35));
   INV1S U148 (.O(n117),
	.I(n40));
   AO22 U149 (.O(n108),
	.A1(out_inst_2[8]),
	.A2(FE_DBTN3_n41),
	.B1(out_inst_0[8]),
	.B2(FE_DBTN2_n48));
   INV1S U150 (.O(N23),
	.I(out_inst_1[7]));
   INV1S U151 (.O(N29),
	.I(out_inst_1[1]));
   INV1S U152 (.O(N28),
	.I(out_inst_1[2]));
   INV1S U153 (.O(N27),
	.I(out_inst_1[3]));
   INV1S U154 (.O(N26),
	.I(out_inst_1[4]));
   INV1S U155 (.O(N25),
	.I(out_inst_1[5]));
   INV1S U156 (.O(N24),
	.I(out_inst_1[6]));
   ND3 U160 (.O(n42),
	.I1(n123),
	.I2(n124),
	.I3(state_r[2]));
   XNR2HS U161 (.O(n35),
	.I1(inst_r[1]),
	.I2(inst_r[2]));
   INV1S U162 (.O(n123),
	.I(state_r[0]));
   INV1S U163 (.O(n120),
	.I(state_r[2]));
   ND3 U164 (.O(n41),
	.I1(n123),
	.I2(n120),
	.I3(state_r[1]));
   INV1S U165 (.O(n124),
	.I(state_r[1]));
   OAI22S U166 (.O(n88),
	.A1(n29),
	.A2(n123),
	.B1(n25),
	.B2(n30));
   NR2 U167 (.O(n29),
	.I1(n25),
	.I2(n27));
   MOAI1S U168 (.O(n87),
	.A1(n25),
	.A2(n26),
	.B1(n27),
	.B2(state_r[1]));
   MOAI1S U169 (.O(n89),
	.A1(n25),
	.A2(n31),
	.B1(n27),
	.B2(state_r[2]));
   NR2 U170 (.O(n45),
	.I1(n35),
	.I2(inst_r[2]));
   ND3 U171 (.O(n47),
	.I1(n124),
	.I2(n120),
	.I3(state_r[0]));
   ND3 U172 (.O(n38),
	.I1(state_r[2]),
	.I2(n123),
	.I3(state_r[1]));
   ND3 U173 (.O(n43),
	.I1(inst_r[1]),
	.I2(inst_r[0]),
	.I3(inst_r[2]));
   ND3 U174 (.O(n36),
	.I1(state_r[0]),
	.I2(n120),
	.I3(state_r[1]));
   INV1S U175 (.O(n119),
	.I(inst_r[0]));
   ND3 U176 (.O(n39),
	.I1(state_r[0]),
	.I2(n124),
	.I3(state_r[2]));
   NR2 U177 (.O(n37),
	.I1(n119),
	.I2(inst_r[1]));
   OA12 U178 (.O(n40),
	.A1(n46),
	.B1(inst_r[2]),
	.B2(inst_r[0]));
   OR2 U179 (.O(n46),
	.I1(inst_r[2]),
	.I2(inst_r[1]));
   MAOI1 U180 (.O(n85),
	.A1(FE_DBTN4_n39),
	.A2(n86),
	.B1(n42),
	.B2(out_inst_1[0]));
   AOI22S U181 (.O(n84),
	.A1(out_inst_1[0]),
	.A2(FE_DBTN0_n91),
	.B1(out_inst_1[0]),
	.B2(FE_DBTN1_n90));
   MAOI1 U182 (.O(n81),
	.A1(FE_DBTN4_n39),
	.A2(n82),
	.B1(n42),
	.B2(out_inst_1[1]));
   AOI22S U183 (.O(n80),
	.A1(N32),
	.A2(FE_DBTN0_n91),
	.B1(out_inst_1[1]),
	.B2(FE_DBTN1_n90));
   MAOI1 U184 (.O(n77),
	.A1(FE_DBTN4_n39),
	.A2(n78),
	.B1(n42),
	.B2(out_inst_1[2]));
   AOI22S U185 (.O(n76),
	.A1(N33),
	.A2(FE_DBTN0_n91),
	.B1(out_inst_1[2]),
	.B2(FE_DBTN1_n90));
   MAOI1 U186 (.O(n73),
	.A1(FE_DBTN4_n39),
	.A2(n74),
	.B1(n42),
	.B2(out_inst_1[3]));
   AOI22S U187 (.O(n72),
	.A1(N34),
	.A2(FE_DBTN0_n91),
	.B1(out_inst_1[3]),
	.B2(FE_DBTN1_n90));
   MAOI1 U188 (.O(n69),
	.A1(FE_DBTN4_n39),
	.A2(n70),
	.B1(n42),
	.B2(out_inst_1[4]));
   AOI22S U189 (.O(n68),
	.A1(N35),
	.A2(FE_DBTN0_n91),
	.B1(out_inst_1[4]),
	.B2(FE_DBTN1_n90));
   MAOI1 U190 (.O(n65),
	.A1(FE_DBTN4_n39),
	.A2(n66),
	.B1(n42),
	.B2(out_inst_1[5]));
   AOI22S U191 (.O(n64),
	.A1(N36),
	.A2(FE_DBTN0_n91),
	.B1(out_inst_1[5]),
	.B2(FE_DBTN1_n90));
   MAOI1 U192 (.O(n61),
	.A1(FE_DBTN4_n39),
	.A2(n62),
	.B1(n42),
	.B2(out_inst_1[6]));
   AOI22S U193 (.O(n60),
	.A1(N37),
	.A2(FE_DBTN0_n91),
	.B1(out_inst_1[6]),
	.B2(FE_DBTN1_n90));
   MOAI1S U194 (.O(n54),
	.A1(out_inst_1[7]),
	.A2(n42),
	.B1(out_inst_2[7]),
	.B2(FE_DBTN3_n41));
   XOR2HS U195 (.O(n58),
	.I1(out_inst_3[6]),
	.I2(data_b_r[7]));
   XOR2HS U196 (.O(n86),
	.I1(data_b_r[0]),
	.I2(\data_a_r[0] ));
   XOR2HS U197 (.O(n82),
	.I1(out_inst_3[0]),
	.I2(data_b_r[1]));
   XOR2HS U198 (.O(n78),
	.I1(out_inst_3[1]),
	.I2(data_b_r[2]));
   XOR2HS U199 (.O(n74),
	.I1(out_inst_3[2]),
	.I2(data_b_r[3]));
   XOR2HS U200 (.O(n70),
	.I1(out_inst_3[3]),
	.I2(data_b_r[4]));
   XOR2HS U201 (.O(n66),
	.I1(out_inst_3[4]),
	.I2(data_b_r[5]));
   XOR2HS U202 (.O(n62),
	.I1(out_inst_3[5]),
	.I2(data_b_r[6]));
   TIE0 U207 (.O(n2));
   INV1S U208 (.O(N30),
	.I(out_inst_1[0]));
endmodule

module CHIP (
	clk_p_i, 
	reset_n_i, 
	data_a_i, 
	data_b_i, 
	inst_i, 
	data_o);
   input clk_p_i;
   input reset_n_i;
   input [7:0] data_a_i;
   input [7:0] data_b_i;
   input [2:0] inst_i;
   output [15:0] data_o;

   // Internal wires
   wire [7:0] i_data_a_i;
   wire [7:0] i_data_b_i;
   wire [2:0] i_inst_i;
   wire [15:0] i_data_o;
   wire i_clk_p_i;
   wire i_reset_n_i;
   wire n_logic0;
   wire n_logic1;

   alu alu_in (.clk_p_i(i_clk_p_i),
	.reset_n_i(i_reset_n_i),
	.data_a_i(i_data_a_i),
	.data_b_i(i_data_b_i),
	.inst_i(i_inst_i),
	.data_o(i_data_o));
   TIE0 ipad_n_logic0 (.O(n_logic0));
   TIE1 ipad_n_logic1 (.O(n_logic1));
   XMD ipad_clk_p_i (.O(i_clk_p_i),
	.I(clk_p_i),
	.PU(n_logic0),
	.PD(n_logic0),
	.SMT(n_logic0));
   XMD ipad_reset_n_i (.O(i_reset_n_i),
	.I(reset_n_i),
	.PU(n_logic0),
	.PD(n_logic0),
	.SMT(n_logic0));
   XMD ipad_inst_i_0 (.O(i_inst_i[0]),
	.I(inst_i[0]),
	.PU(n_logic0),
	.PD(n_logic0),
	.SMT(n_logic0));
   XMD ipad_inst_i_1 (.O(i_inst_i[1]),
	.I(inst_i[1]),
	.PU(n_logic0),
	.PD(n_logic0),
	.SMT(n_logic0));
   XMD ipad_inst_i_2 (.O(i_inst_i[2]),
	.I(inst_i[2]),
	.PU(n_logic0),
	.PD(n_logic0),
	.SMT(n_logic0));
   XMD ipad_data_a_i_0 (.O(i_data_a_i[0]),
	.I(data_a_i[0]),
	.PU(n_logic0),
	.PD(n_logic0),
	.SMT(n_logic0));
   XMD ipad_data_a_i_1 (.O(i_data_a_i[1]),
	.I(data_a_i[1]),
	.PU(n_logic0),
	.PD(n_logic0),
	.SMT(n_logic0));
   XMD ipad_data_a_i_2 (.O(i_data_a_i[2]),
	.I(data_a_i[2]),
	.PU(n_logic0),
	.PD(n_logic0),
	.SMT(n_logic0));
   XMD ipad_data_a_i_3 (.O(i_data_a_i[3]),
	.I(data_a_i[3]),
	.PU(n_logic0),
	.PD(n_logic0),
	.SMT(n_logic0));
   XMD ipad_data_a_i_4 (.O(i_data_a_i[4]),
	.I(data_a_i[4]),
	.PU(n_logic0),
	.PD(n_logic0),
	.SMT(n_logic0));
   XMD ipad_data_a_i_5 (.O(i_data_a_i[5]),
	.I(data_a_i[5]),
	.PU(n_logic0),
	.PD(n_logic0),
	.SMT(n_logic0));
   XMD ipad_data_a_i_6 (.O(i_data_a_i[6]),
	.I(data_a_i[6]),
	.PU(n_logic0),
	.PD(n_logic0),
	.SMT(n_logic0));
   XMD ipad_data_a_i_7 (.O(i_data_a_i[7]),
	.I(data_a_i[7]),
	.PU(n_logic0),
	.PD(n_logic0),
	.SMT(n_logic0));
   XMD ipad_data_b_i_0 (.O(i_data_b_i[0]),
	.I(data_b_i[0]),
	.PU(n_logic0),
	.PD(n_logic0),
	.SMT(n_logic0));
   XMD ipad_data_b_i_1 (.O(i_data_b_i[1]),
	.I(data_b_i[1]),
	.PU(n_logic0),
	.PD(n_logic0),
	.SMT(n_logic0));
   XMD ipad_data_b_i_2 (.O(i_data_b_i[2]),
	.I(data_b_i[2]),
	.PU(n_logic0),
	.PD(n_logic0),
	.SMT(n_logic0));
   XMD ipad_data_b_i_3 (.O(i_data_b_i[3]),
	.I(data_b_i[3]),
	.PU(n_logic0),
	.PD(n_logic0),
	.SMT(n_logic0));
   XMD ipad_data_b_i_4 (.O(i_data_b_i[4]),
	.I(data_b_i[4]),
	.PU(n_logic0),
	.PD(n_logic0),
	.SMT(n_logic0));
   XMD ipad_data_b_i_5 (.O(i_data_b_i[5]),
	.I(data_b_i[5]),
	.PU(n_logic0),
	.PD(n_logic0),
	.SMT(n_logic0));
   XMD ipad_data_b_i_6 (.O(i_data_b_i[6]),
	.I(data_b_i[6]),
	.PU(n_logic0),
	.PD(n_logic0),
	.SMT(n_logic0));
   XMD ipad_data_b_i_7 (.O(i_data_b_i[7]),
	.I(data_b_i[7]),
	.PU(n_logic0),
	.PD(n_logic0),
	.SMT(n_logic0));
   YA2GSD ipad_data_o_0 (.O(data_o[0]),
	.I(i_data_o[0]),
	.E(n_logic1),
	.E2(n_logic0),
	.E4(n_logic0),
	.E8(n_logic0),
	.SR(n_logic0));
   YA2GSD ipad_data_o_1 (.O(data_o[1]),
	.I(i_data_o[1]),
	.E(n_logic1),
	.E2(n_logic0),
	.E4(n_logic0),
	.E8(n_logic0),
	.SR(n_logic0));
   YA2GSD ipad_data_o_2 (.O(data_o[2]),
	.I(i_data_o[2]),
	.E(n_logic1),
	.E2(n_logic0),
	.E4(n_logic0),
	.E8(n_logic0),
	.SR(n_logic0));
   YA2GSD ipad_data_o_3 (.O(data_o[3]),
	.I(i_data_o[3]),
	.E(n_logic1),
	.E2(n_logic0),
	.E4(n_logic0),
	.E8(n_logic0),
	.SR(n_logic0));
   YA2GSD ipad_data_o_4 (.O(data_o[4]),
	.I(i_data_o[4]),
	.E(n_logic1),
	.E2(n_logic0),
	.E4(n_logic0),
	.E8(n_logic0),
	.SR(n_logic0));
   YA2GSD ipad_data_o_5 (.O(data_o[5]),
	.I(i_data_o[5]),
	.E(n_logic1),
	.E2(n_logic0),
	.E4(n_logic0),
	.E8(n_logic0),
	.SR(n_logic0));
   YA2GSD ipad_data_o_6 (.O(data_o[6]),
	.I(i_data_o[6]),
	.E(n_logic1),
	.E2(n_logic0),
	.E4(n_logic0),
	.E8(n_logic0),
	.SR(n_logic0));
   YA2GSD ipad_data_o_7 (.O(data_o[7]),
	.I(i_data_o[7]),
	.E(n_logic1),
	.E2(n_logic0),
	.E4(n_logic0),
	.E8(n_logic0),
	.SR(n_logic0));
   YA2GSD ipad_data_o_8 (.O(data_o[8]),
	.I(i_data_o[8]),
	.E(n_logic1),
	.E2(n_logic0),
	.E4(n_logic0),
	.E8(n_logic0),
	.SR(n_logic0));
   YA2GSD ipad_data_o_9 (.O(data_o[9]),
	.I(i_data_o[9]),
	.E(n_logic1),
	.E2(n_logic0),
	.E4(n_logic0),
	.E8(n_logic0),
	.SR(n_logic0));
   YA2GSD ipad_data_o_10 (.O(data_o[10]),
	.I(i_data_o[10]),
	.E(n_logic1),
	.E2(n_logic0),
	.E4(n_logic0),
	.E8(n_logic0),
	.SR(n_logic0));
   YA2GSD ipad_data_o_11 (.O(data_o[11]),
	.I(i_data_o[11]),
	.E(n_logic1),
	.E2(n_logic0),
	.E4(n_logic0),
	.E8(n_logic0),
	.SR(n_logic0));
   YA2GSD ipad_data_o_12 (.O(data_o[12]),
	.I(i_data_o[12]),
	.E(n_logic1),
	.E2(n_logic0),
	.E4(n_logic0),
	.E8(n_logic0),
	.SR(n_logic0));
   YA2GSD ipad_data_o_13 (.O(data_o[13]),
	.I(i_data_o[13]),
	.E(n_logic1),
	.E2(n_logic0),
	.E4(n_logic0),
	.E8(n_logic0),
	.SR(n_logic0));
   YA2GSD ipad_data_o_14 (.O(data_o[14]),
	.I(i_data_o[14]),
	.E(n_logic1),
	.E2(n_logic0),
	.E4(n_logic0),
	.E8(n_logic0),
	.SR(n_logic0));
   YA2GSD ipad_data_o_15 (.O(data_o[15]),
	.I(i_data_o[15]),
	.E(n_logic1),
	.E2(n_logic0),
	.E4(n_logic0),
	.E8(n_logic0),
	.SR(n_logic0));
endmodule

